### ISSUE TITLE
Copying a build, then deleting an item from the copied build, may result in auth error

### ISSUE THREAD

**Issue by lightyearsaway** [samlee405/dofus-lab#106]
"after copying a build, you can't remove items, only replace them"

![](https://cdn.discordapp.com/attachments/694305331232112791/705950769333010512/unknown.png)

To my knowledge, the checks for adding, replacing, and deleting items are all the same, so I'm not sure as to what the cause of this bug is yet, and I'm unable to reproduce for now.

Seems a little flaky, the bug reporter refreshed and said it was working fine, and disabling a privacy extension seemed to have fixed the issue, but re-enabling it did not cause the problem to come back.

**Comment by sfxll** [comment]
Steps to reproduce: 
1. Visit https://www.dofuslab.io/build/c4b965eb-f233-4c40-8730-b7cfb8fe433b
     1a. If this build no longer exists, visit a build created and shared by another user (anonymous?)
2. Create a copy of the set
3. Attempt to remove any piece of gear

**Comment by sfxll** [comment]
It seems this issue is present even on the same session that the issue has disappeared (ie: refresh the page so the removal now works, and visit the site again in a new tab)

This issue is exclusive to the initial loading of the copied set, regardless of session.
